### ISSUE TITLE
YNABBER hanging after "found $x account" log

### ISSUE THREAD

**Issue by CanYumusak** [martinohansen/ynabber#61]
Heyhey,

I regularly have the problem that my YNABBER is doing nothing after showing the following logs:

```
2024/01/03 17:31:26 Successfully sent 257 transaction(s) to YNAB. 0 got skipped and 114 failed.
2024/01/03 17:31:26 Run succeeded
2024/01/03 17:31:26 Waiting 5m0s before running again...
2024/01/03 17:36:27 Found 2 accounts
```

The docker container shows no action after 2024/01/03. 

My requisiton status seems to be "LN" according to the persisted json file. 

Any ideas?

**Comment by martinohansen** [comment]
How does your YNAB_ACCOUNTMAP setting look?

**Comment by CanYumusak** [comment]
The errors stem from the fact that I have 2 accounts and only 1 is mapped, the other is unmapped (willingly, since its a shared account). 

The programm runs as expected for some time (with the XXX failed logs) and stops after a few runs (~ a day later?). WIll run with debug settings on and get back

**Comment by CanYumusak** [comment]
Did the same with debug mode which renders more or less the same issue:

```

{"data":{"transaction_ids":[],"duplicate_import_ids":[...],"transactions":[],"server_knowledge":3247}}
2024/01/07 14:46:14 Successfully sent 255 transaction(s) to YNAB. 0 got skipped and 124 failed.
2024/01/07 14:46:14 Run succeeded
2024/01/07 14:46:14 Waiting 5m0s before running again...
2024/01/07 14:51:14 Found 2 accounts
➜  ~ 

```

**Comment by martinohansen** [comment]
It seems like it gets stuck when it reads the account metadata, not sure why but it could be due to a timeout. I updated the Nordigen client with a timeout of 60s (currently it will wait forever) lets see if that helps.

Can you run with this version to see if it fixes the issue?

```
go install github.com/martinohansen/ynabber/cmd/ynabber@8d9c462

# Or if you use docker
docker pull ghcr.io/martinohansen/ynabber:pr-63
```

I also updated my install to run off this version, but I didn't run into the same problem.

**Comment by CanYumusak** [comment]
Trying this out, thanks for the fix!

**Comment by CanYumusak** [comment]
@martinohansen I guess you were right:

> 2024/01/14 00:43:50 Found 2 accounts
2024/01/14 00:43:50 Reading transactions from account: DEXXXXXXX
panic: reading: failed to get transactions: Get "https://ob.nordigen.com/api/v2/accounts/9eec0b53-6824-455c-a4bf-bba5a298e4c1/transactions/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

The next step would be ignoring that error or understand it better?

**Comment by hpernu** [comment]
Chiming in a bit: in a case like this since ynabber is essentially running in 'daemon mode' falling back to waiting for next fetch cycle would be the most logical. I.e. in essence this would work the same way as succesfull fetch (with no new transactions but most of the time there are none anyway) with the only difference been the error in the logs/output. Just have to make certain it does this only with timeouts - other non-transient failures should still cause ynabber to exit.

If the interval is set to to zero though (my use case), then ynabber should probably return an error and exit(it would exit anyway).

**Comment by martinohansen** [comment]
We could make it retry but I doubt it will work since the configuration before waited forever and never got a response. Is something in your setup intercepting the connection? 

Until we understand better what's going on I think the best solution is to let it crash and let a supervisor (e.g. systemd) restart the process. My bank sometimes fails to respond which similarly crashes the process: 

```
2023-12-30 20:14:57.001 virus ynabber.service panic: couldn't read from nordigen: failed to get transactions: APIError 503 {"summary":"Couldn't update account transactions","detail":"Couldn't connect to Institution","status_code":503,"type":"ConnectionError"} 
```

**Comment by CanYumusak** [comment]
> Until we understand better what's going on I think the best solution is to let it crash and let a supervisor (e.g. systemd) restart the process. 

Apologize for the seemingly easy question but would that be part of the docker container config when used via docker? Do docker containers have systemd running? 🤔 

> Is something in your setup intercepting the connection?

Not that I know of. This is my regular vServer hosted on netcup. The curious part is that the connection stops working after a somewhat reproducible amount of connections.

**Comment by martinohansen** [comment]
> > Until we understand better what's going on I think the best solution is to let it crash and let a supervisor (e.g. systemd) restart the process.
> 
> Apologize for the seemingly easy question but would that be part of the docker container config when used via docker? Do docker containers have systemd running? 🤔
> 
> > Is something in your setup intercepting the connection?
> 
> Not that I know of. This is my regular vServer hosted on netcup. The curious part is that the connection stops working after a somewhat reproducible amount of connections.

Im not using Docker, I use Systemd instead to run and manage the process.

For docker you need to add the `--restart` flag to the `docker run` command if I'm not mistaken[1]. Something like this:

```
docker run -d --restart unless-stopped ghcr.io/martinohansen/ynabber:latest
```

[1]https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by hpernu** [comment]
> > > Until we understand better what's going on I think the best solution is to let it crash and let a supervisor (e.g. systemd) restart the process.
> > 
> > 
> > Apologize for the seemingly easy question but would that be part of the docker container config when used via docker? Do docker containers have systemd running? 🤔
> > > Is something in your setup intercepting the connection?
> > 
> > 
> > Not that I know of. This is my regular vServer hosted on netcup. The curious part is that the connection stops working after a somewhat reproducible amount of connections.
> 
> Im not using Docker, I use Systemd instead to run and manage the process.
> 
> For docker you need to add the `--restart` flag to the `docker run` command if I'm not mistaken[1]. Something like this:
> 
> ```
> docker run -d --restart unless-stopped ghcr.io/martinohansen/ynabber:latest
> ```
> 
> [1]https://docs.docker.com/config/containers/start-containers-automatically/

Better yet, use docker run --rm --user $(id -u) ... 
That way, the layers will be removed when stopped removing dangling images and running as user will avoid root owned files if you bind mount ...

But as a reply to the original question: docker containers do not usually have systemd. There are exceptions but ynabber image is not one of them. It is essentially just the ynabber command with minimal libraries to run it.

**Comment by martinohansen** [comment]
Fixed in v0.7.1

**Comment by martinohansen** [comment]
I've started to run into the same issue, I'm running v0.7.2. @CanYumusak do you still see it and what version do you run?

**Comment by CanYumusak** [comment]
Still ran your branch (pr-63); My issue is still not resolved since even with `--restart unless-stopped` the docker container is not crashing but instead just the program running into it. Wanted to look at it once I have time.

Pulled & started v0.7.2 now

**Comment by martinohansen** [comment]
> Need a timeout on the connection? I.e. if no reply within XX seconds, exit ... docker --restart unless-stopped would then work.

We should have added a timeout, but it still happens sometimes. I'll trying and profile it next time it happens to see whats going on.

**Comment by CanYumusak** [comment]
> > Need a timeout on the connection? I.e. if no reply within XX seconds, exit ... docker --restart unless-stopped would then work.
> 
> We should have added a timeout, but it still happens sometimes. I'll try and profile it next time it happens to see whats going on.

Any insights here? Might be a stupid Q but can this be related to the new URL they advertised through mail?

**Comment by martinohansen** [comment]
@CanYumusak I think I finally found the cause for this. I made a PR to the upstream lib, once that's merged I will cut a new version.
